name: intl_cli
description: A CLI tool for Flutter/Dart internationalization.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  analyzer: ^6.3.0
  path: ^1.8.0
  yaml: ^3.1.1
  args: ^2.4.2

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  intl_cli: intl_cli

