name: intl_cli
description: A powerful command-line tool for automating Flutter/Dart internationalization. Extract hardcoded strings, generate ARB files, and refactor code with ease.
version: 1.0.1
homepage: https://github.com/Ahtsham0715/intl_cli
repository: https://github.com/Ahtsham0715/intl_cli
issue_tracker: https://github.com/Ahtsham0715/intl_cli/issues
documentation: https://github.com/Ahtsham0715/intl_cli#readme

topics:
  - cli
  - internationalization
  - i18n
  - flutter
  - localization

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  analyzer: ^6.3.0
  path: ^1.8.0
  yaml: ^3.1.1
  args: ^2.4.2

  flutter_localizations:
    sdk: flutter
dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

executables:
  intl_cli: intl_cli

